# Generated by Django 3.2.15 on 2023-02-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('admin_commands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveManagementCommand',
            fields=[
            ],
            options={
                'verbose_name': 'Active Management Command',
                'verbose_name_plural': 'Active Management Commands',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admin_commands.managementcommand',),
        ),
        migrations.RemoveField(
            model_name='managementcommand',
            name='deleted',
        ),
        migrations.AddField(
            model_name='managementcommand',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
